import {Inter} from "next/font/google";
import "./globals.css";
import {Providers} from "@/app/Providers";
import Layout from "@/app/components/layout/layout";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <Providers>
            <html lang="en">
            <head>
                <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
            </head>
            <body className=''>
            <header>
            <Layout/>
            </header>
            {children}
            </body>
            </html>
        </Providers>
    );
}
